//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public Definition()
        {
            this.UpDownVotes = new HashSet<UpDownVote>();
        }
    
        public int Id { get; set; }
        public int EnglishId { get; set; }
        public int CountryId { get; set; }
        public string Definition1 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual English English { get; set; }
        public virtual ICollection<UpDownVote> UpDownVotes { get; set; }
    }
}
