//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class English
    {
        public English()
        {
            this.Definitions = new HashSet<Definition>();
        }
    
        public int Id { get; set; }
        public string Term { get; set; }
    
        public virtual ICollection<Definition> Definitions { get; set; }
    }
}
