//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpDownVote
    {
        public int Id { get; set; }
        public int DefinitionId { get; set; }
        public Nullable<int> UpVotes { get; set; }
        public Nullable<int> DownVotes { get; set; }
    
        public virtual Definition Definition { get; set; }
    }
}
